In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
Abi= np.array([1,2,3,4,5])  #comparing numpy to pandas

In [4]:
Abi

array([1, 2, 3, 4, 5])

In [5]:
pd.Series([10,20,30,40,50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
Abi=pd.Series([10,20,30,40,50])

In [7]:
Abi

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [8]:
type(Abi)

pandas.core.series.Series

In [9]:
Abi.axes

[RangeIndex(start=0, stop=5, step=1)]

In [10]:
Abi.dtype

dtype('int64')

In [11]:
Abi.size

5

In [12]:
Abi.ndim #shows the number of array

1

In [13]:
Abi.values

array([10, 20, 30, 40, 50], dtype=int64)

In [14]:
Abi.head(2)

0    10
1    20
dtype: int64

In [15]:
Abi.head()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [16]:
import numpy as np

In [17]:
mytail = np.array([8,9,7,10,14,2,8])

In [18]:
mytail

array([ 8,  9,  7, 10, 14,  2,  8])

In [19]:
mytail = pd.Series(mytail)

In [20]:
mytail

0     8
1     9
2     7
3    10
4    14
5     2
6     8
dtype: int32

In [21]:
import pandas as pd

In [22]:
pd.Series([13,214,210,440,53])

0     13
1    214
2    210
3    440
4     53
dtype: int64

In [23]:
pd.Series([13,214,210,440,53],index=[4,6,7,3,87,])

4      13
6     214
7     210
3     440
87     53
dtype: int64

In [25]:
Abi=pd.Series([13,214,210,440,53],index=["first","second","third","fourth","fifth"])

In [26]:
Abi

first      13
second    214
third     210
fourth    440
fifth      53
dtype: int64

In [30]:
Abi[3]

440

In [31]:
Abi['fifth']

53

#concat


In [34]:
s1=pd.Series([2,3,55,2,6,44])
s2=pd.Series([421,325,3426,2,1,4,42])

In [35]:
pd.concat([s1,s2])

0       2
1       3
2      55
3       2
4       6
5      44
0     421
1     325
2    3426
3       2
4       1
5       4
6      42
dtype: int64

In [36]:
Abi=pd.Series([13,214,210,440,53],index=["first","second","third","fourth","fifth"])

In [37]:
Abi

first      13
second    214
third     210
fourth    440
fifth      53
dtype: int64

In [38]:
Abi['first']

13

In [39]:
Abi.keys

<bound method Series.keys of first      13
second    214
third     210
fourth    440
fifth      53
dtype: int64>

In [40]:
list(Abi.items())

[('first', 13),
 ('second', 214),
 ('third', 210),
 ('fourth', 440),
 ('fifth', 53)]

In [49]:
s1 = pd.Series([2,3,55,2,6,44])
s1

0     2
1     3
2    55
3     2
4     6
5    44
dtype: int64

In [50]:
3 in s1

True

In [51]:
34 in s1

False

In [52]:
s1[[2,4]]

2    55
4     6
dtype: int64

In [53]:
s1[[1,5]]

1     3
5    44
dtype: int64

In [57]:
s1[[2]]

2    55
dtype: int64

In [58]:
s1[2]

55

In [59]:
s1[0]=4

In [60]:
s1

0     4
1     3
2    55
3     2
4     6
5    44
dtype: int64

In [61]:
pd.DataFrame({'Name': ["Mellon","Josh", "Mary"], 'Age': [17,34,45],'Location':['Kotei','Tech','Ayeduase']})

Name  Age  Location
0  Mellon   17     Kotei
1    Josh   34      Tech
2    Mary   45  Ayeduase

In [62]:
dic = ({'Name': ["Mellon","Josh", "Mary"], 'Age': [17,34,45],'Location':['Kotei','Tech','Ayeduase']})
dataframe = pd.DataFrame(dic)
dataframe

Name  Age  Location
0  Mellon   17     Kotei
1    Josh   34      Tech
2    Mary   45  Ayeduase

In [63]:
dataframe['Age']

0    17
1    34
2    45
Name: Age, dtype: int64

In [66]:
dataframe.Age

0    17
1    34
2    45
Name: Age, dtype: int64

In [67]:
dataframe[['Age']] #we use double square bracket when we want it in a  dataframe

Age
0   17
1   34
2   45

In [68]:
l = [23,35423,25235,325,235,75]
df = pd.DataFrame(l,columns=["variable"])
df

variable
0        23
1     35423
2     25235
3       325
4       235
5        75

In [69]:
names = ["John","Mike","Julia","Anastacia"]
df = pd.DataFrame(names,columns=["Names"]) 
df

Names
0       John
1       Mike
2      Julia
3  Anastacia

In [71]:
arr = np.array([5,6,7,3,2,1,2,42,5]).reshape(3,3,)
arr

array([[ 5,  6,  7],
       [ 3,  2,  1],
       [ 2, 42,  5]])

In [73]:
pd.DataFrame(data=arr,columns=["Variable_1","Variable_2","Variable_3"])

Variable_1  Variable_2  Variable_3
0           5           6           7
1           3           2           1
2           2          42           5

In [74]:
Abi = pd.DataFrame(arr,columns=["Variable_1","Variable_2","Variable_3"])
Abi

Variable_1  Variable_2  Variable_3
0           5           6           7
1           3           2           1
2           2          42           5

In [75]:
Abi.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['Variable_1', 'Variable_2', 'Variable_3'], dtype='object')]

In [76]:
Abi.shape 

(3, 3)

In [77]:
Abi.ndim

2

In [78]:
Abi.size

9

In [79]:
Abi.columns

Index(['Variable_1', 'Variable_2', 'Variable_3'], dtype='object')

In [80]:
Abi.index

RangeIndex(start=0, stop=3, step=1)

In [82]:
Abi.values

array([[ 5,  6,  7],
       [ 3,  2,  1],
       [ 2, 42,  5]])